#!/bin/bash
sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp ./usr/ucts_180.dtb /boot/overlays/ucts_180.dtbo
sudo cp -rf ./usr/99-calibration.conf-mhs35  /etc/X11/xorg.conf.d/99-calibration.conf
sudo cp ./boot/config-ucts_180.txt /boot/config.txt
sudo reboot
